name: NetherrackDamage
main: netherrackdamage.NetherrackDamage
version: 0.5_01
author: ChrizC
description: NetherrackDamage damages the player when he/she comes into contact with Netherrack.
commands:
  dmgdealt:
    description: Changes damage dealt by Netherrack.
    usage: |
           /dmgdealt NewDamage
  dmgdelay:
    description: Changes the delay between damages by Netherrack.
    usage: |
           /dmgdelay NewDelay
  bootmod:
    description: Enables/disables Boot Modification of Netherrack Damage.
    usage: |
           /bootmod Yes/No